#include "pch.h"
#include "User.h"
#include "User.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::CustomerManagementAppService::implementation
{
    User::User(int32_t id, hstring const& username, hstring const& password, int64_t companyId)
    {
        throw hresult_not_implemented();
    }
    int64_t User::GetId()
    {
        throw hresult_not_implemented();
    }
    hstring User::GetUsername()
    {
        throw hresult_not_implemented();
    }
    hstring User::GetPassword()
    {
        throw hresult_not_implemented();
    }
    int64_t User::GetCompanyId()
    {
        throw hresult_not_implemented();
    }
    void User::SetId(int64_t id)
    {
        throw hresult_not_implemented();
    }
    void User::SetUsername(hstring const& username)
    {
        throw hresult_not_implemented();
    }
    void User::SetPassword(hstring const& password)
    {
        throw hresult_not_implemented();
    }
    void User::SetCompanyId(int64_t companyId)
    {
        throw hresult_not_implemented();
    }
}
