namespace CustomerManagementAppService
{
    [bindable]
    [default_interface]
    runtimeclass Customer 
    {
        Customer();
        Customer(String email, String mobile, String fullname);
        void AddCustomer(Customer customer);
    }
}
