namespace CustomerManagementAppService
{
    [bindable]
    [default_interface]
    runtimeclass User 
    {
        User();
        User(Int32 id, String username, String password, Int64 companyId);
    }
}
