import "AuthUserResultVM.idl";

namespace CustomerManagementAppService
{
    [bindable]
    [default_interface]
    runtimeclass UserService 
    {
        UserService();
        AuthUserResultVM GetUserByID(Int32 Id);
        AuthUserResultVM AuthenticateUser(String username, String password, String company);
        AuthUserResultVM CreateUser(String username, String password, String company);
    }
}
