namespace CustomerManagementAppService
{
    [bindable]
    [default_interface]
    runtimeclass User 
    {
        User();
        User(Int32 id, String username, String password, String company);
        Int64 GetId{ get; };
        String GetUsername{ get; };
        String GetPassword{ get; };
        String GetCompany{ get; };
        void SetId(Int64 id);
        void SetUsername(String username);
        void SetPassword(String password);
        void SetCompany(String company);
    }
}
