namespace CustomerManagementAppService
{
    [bindable]
    [default_interface]
    runtimeclass User 
    {
        User();

        Int32 Id;
        String Username;
        String Password;
        Int64 CompanyID;
    }
}
