// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

void* winrt_make_CustomerManagementAppService_AuthUserResultVM()
{
    return winrt::detach_abi(winrt::make<winrt::CustomerManagementAppService::factory_implementation::AuthUserResultVM>());
}
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    AuthUserResultVM::AuthUserResultVM() :
        AuthUserResultVM(make<CustomerManagementAppService::implementation::AuthUserResultVM>())
    {
    }
}
