// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210930.14

void* winrt_make_CustomerManagementAppService_Class()
{
    return winrt::detach_abi(winrt::make<winrt::CustomerManagementAppService::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    Class::Class() :
        Class(make<CustomerManagementAppService::implementation::Class>())
    {
    }
}
