// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

void* winrt_make_CustomerManagementAppService_Customer()
{
    return winrt::detach_abi(winrt::make<winrt::CustomerManagementAppService::factory_implementation::Customer>());
}
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    Customer::Customer() :
        Customer(make<CustomerManagementAppService::implementation::Customer>())
    {
    }
    Customer::Customer(param::hstring const& email, param::hstring const& mobile, param::hstring const& fullname) :
        Customer(make<CustomerManagementAppService::implementation::Customer>(email, mobile, fullname))
    {
    }
}
