// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#include "winrt/CustomerManagementAppService.h"
namespace winrt::CustomerManagementAppService::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) UserService_base : implements<D, CustomerManagementAppService::UserService, I...>
    {
        using base_type = UserService_base;
        using class_type = CustomerManagementAppService::UserService;
        using implements_type = typename UserService_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"CustomerManagementAppService.UserService";
        }
    };
}
namespace winrt::CustomerManagementAppService::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) UserServiceT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = CustomerManagementAppService::UserService;

        hstring GetRuntimeClassName() const
        {
            return L"CustomerManagementAppService.UserService";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_USERSERVICE_XAML_G_H) || __has_include("UserService.xaml.g.h")
#include "UserService.xaml.g.h"
#else

namespace winrt::CustomerManagementAppService::implementation
{
    template <typename D, typename... I>
    using UserServiceT = UserService_base<D, I...>;
}

#endif
