// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#include "winrt/CustomerManagementAppService.h"
namespace winrt::CustomerManagementAppService::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) User_base : implements<D, CustomerManagementAppService::User, I...>
    {
        using base_type = User_base;
        using class_type = CustomerManagementAppService::User;
        using implements_type = typename User_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"CustomerManagementAppService.User";
        }
    };
}
namespace winrt::CustomerManagementAppService::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) UserT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = CustomerManagementAppService::User;

        hstring GetRuntimeClassName() const
        {
            return L"CustomerManagementAppService.User";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_USER_XAML_G_H) || __has_include("User.xaml.g.h")
#include "User.xaml.g.h"
#else

namespace winrt::CustomerManagementAppService::implementation
{
    template <typename D, typename... I>
    using UserT = User_base<D, I...>;
}

#endif
