// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

void* winrt_make_CustomerManagementAppService_UserService()
{
    return winrt::detach_abi(winrt::make<winrt::CustomerManagementAppService::factory_implementation::UserService>());
}
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    UserService::UserService() :
        UserService(make<CustomerManagementAppService::implementation::UserService>())
    {
    }
}
