// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210930.14

void* winrt_make_CustomerManagementAppData_Class()
{
    return winrt::detach_abi(winrt::make<winrt::CustomerManagementAppData::factory_implementation::Class>());
}
WINRT_EXPORT namespace winrt::CustomerManagementAppData
{
    Class::Class() :
        Class(make<CustomerManagementAppData::implementation::Class>())
    {
    }
}
