// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementApp_H
#define WINRT_CustomerManagementApp_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.211028.7"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.211028.7"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/CustomerManagementApp.2.h"
namespace winrt::impl
{
}
WINRT_EXPORT namespace winrt::CustomerManagementApp
{
    inline XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(impl::call_factory_cast<XamlMetaDataProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), XamlMetaDataProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<XamlMetaDataProvider>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::CustomerManagementApp::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
