// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementAppService_2_H
#define WINRT_CustomerManagementAppService_2_H
#include "winrt/impl/CustomerManagementAppService.1.h"
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    struct __declspec(empty_bases) User : winrt::CustomerManagementAppService::IUser
    {
        User(std::nullptr_t) noexcept {}
        User(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CustomerManagementAppService::IUser(ptr, take_ownership_from_abi) {}
        User();
    };
}
#endif
