// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementAppService_1_H
#define WINRT_CustomerManagementAppService_1_H
#include "winrt/impl/CustomerManagementAppService.0.h"
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    struct __declspec(empty_bases) IUser :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUser>
    {
        IUser(std::nullptr_t = nullptr) noexcept {}
        IUser(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
