// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementAppService_0_H
#define WINRT_CustomerManagementAppService_0_H
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    struct IAuthUserResultVM;
    struct IUser;
    struct IUserFactory;
    struct IUserService;
    struct AuthUserResultVM;
    struct User;
    struct UserService;
}
namespace winrt::impl
{
    template <> struct category<winrt::CustomerManagementAppService::IAuthUserResultVM>{ using type = interface_category; };
    template <> struct category<winrt::CustomerManagementAppService::IUser>{ using type = interface_category; };
    template <> struct category<winrt::CustomerManagementAppService::IUserFactory>{ using type = interface_category; };
    template <> struct category<winrt::CustomerManagementAppService::IUserService>{ using type = interface_category; };
    template <> struct category<winrt::CustomerManagementAppService::AuthUserResultVM>{ using type = class_category; };
    template <> struct category<winrt::CustomerManagementAppService::User>{ using type = class_category; };
    template <> struct category<winrt::CustomerManagementAppService::UserService>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::AuthUserResultVM> = L"CustomerManagementAppService.AuthUserResultVM";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::User> = L"CustomerManagementAppService.User";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::UserService> = L"CustomerManagementAppService.UserService";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::IAuthUserResultVM> = L"CustomerManagementAppService.IAuthUserResultVM";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::IUser> = L"CustomerManagementAppService.IUser";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::IUserFactory> = L"CustomerManagementAppService.IUserFactory";
    template <> inline constexpr auto& name_v<winrt::CustomerManagementAppService::IUserService> = L"CustomerManagementAppService.IUserService";
    template <> inline constexpr guid guid_v<winrt::CustomerManagementAppService::IAuthUserResultVM>{ 0x7E6BFD78,0x6255,0x5F24,{ 0xAC,0x3F,0x57,0x2D,0x2A,0x30,0x56,0x63 } }; // 7E6BFD78-6255-5F24-AC3F-572D2A305663
    template <> inline constexpr guid guid_v<winrt::CustomerManagementAppService::IUser>{ 0x276B72AD,0x3FE2,0x5A28,{ 0xA5,0x79,0xF4,0x10,0xB3,0x6D,0x33,0x1B } }; // 276B72AD-3FE2-5A28-A579-F410B36D331B
    template <> inline constexpr guid guid_v<winrt::CustomerManagementAppService::IUserFactory>{ 0xAEDED7B0,0x1057,0x5862,{ 0xB1,0xAC,0x91,0xC4,0xF6,0x09,0x8C,0x61 } }; // AEDED7B0-1057-5862-B1AC-91C4F6098C61
    template <> inline constexpr guid guid_v<winrt::CustomerManagementAppService::IUserService>{ 0xEA3CA911,0x38EE,0x5D72,{ 0x96,0xA1,0xC7,0x4E,0x28,0x09,0x7A,0xF6 } }; // EA3CA911-38EE-5D72-96A1-C74E28097AF6
    template <> struct default_interface<winrt::CustomerManagementAppService::AuthUserResultVM>{ using type = winrt::CustomerManagementAppService::IAuthUserResultVM; };
    template <> struct default_interface<winrt::CustomerManagementAppService::User>{ using type = winrt::CustomerManagementAppService::IUser; };
    template <> struct default_interface<winrt::CustomerManagementAppService::UserService>{ using type = winrt::CustomerManagementAppService::IUserService; };
    template <> struct abi<winrt::CustomerManagementAppService::IAuthUserResultVM>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_IsSuccessful(bool*) noexcept = 0;
            virtual int32_t __stdcall put_IsSuccessful(bool) noexcept = 0;
            virtual int32_t __stdcall get_Message(void**) noexcept = 0;
            virtual int32_t __stdcall put_Message(void*) noexcept = 0;
            virtual int32_t __stdcall get_UserInfo(void**) noexcept = 0;
            virtual int32_t __stdcall put_UserInfo(void*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CustomerManagementAppService::IUser>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_GetId(int64_t*) noexcept = 0;
            virtual int32_t __stdcall get_GetUsername(void**) noexcept = 0;
            virtual int32_t __stdcall get_GetPassword(void**) noexcept = 0;
            virtual int32_t __stdcall get_GetCompanyId(int64_t*) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CustomerManagementAppService::IUserFactory>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall CreateInstance(int32_t, void*, void*, int64_t, void**) noexcept = 0;
        };
    };
    template <> struct abi<winrt::CustomerManagementAppService::IUserService>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall GetUserByID(int32_t, void**) noexcept = 0;
            virtual int32_t __stdcall AuthenticateUser(void*, void*, int64_t, void**) noexcept = 0;
            virtual int32_t __stdcall CreateUser(void*, void*, int64_t, void**) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_CustomerManagementAppService_IAuthUserResultVM
    {
        [[nodiscard]] WINRT_IMPL_AUTO(bool) IsSuccessful() const;
        WINRT_IMPL_AUTO(void) IsSuccessful(bool value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(hstring) Message() const;
        WINRT_IMPL_AUTO(void) Message(param::hstring const& value) const;
        [[nodiscard]] WINRT_IMPL_AUTO(winrt::CustomerManagementAppService::User) UserInfo() const;
        WINRT_IMPL_AUTO(void) UserInfo(winrt::CustomerManagementAppService::User const& value) const;
    };
    template <> struct consume<winrt::CustomerManagementAppService::IAuthUserResultVM>
    {
        template <typename D> using type = consume_CustomerManagementAppService_IAuthUserResultVM<D>;
    };
    template <typename D>
    struct consume_CustomerManagementAppService_IUser
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int64_t) GetId() const;
        [[nodiscard]] WINRT_IMPL_AUTO(hstring) GetUsername() const;
        [[nodiscard]] WINRT_IMPL_AUTO(hstring) GetPassword() const;
        [[nodiscard]] WINRT_IMPL_AUTO(int64_t) GetCompanyId() const;
    };
    template <> struct consume<winrt::CustomerManagementAppService::IUser>
    {
        template <typename D> using type = consume_CustomerManagementAppService_IUser<D>;
    };
    template <typename D>
    struct consume_CustomerManagementAppService_IUserFactory
    {
        WINRT_IMPL_AUTO(winrt::CustomerManagementAppService::User) CreateInstance(int32_t id, param::hstring const& username, param::hstring const& password, int64_t companyId) const;
    };
    template <> struct consume<winrt::CustomerManagementAppService::IUserFactory>
    {
        template <typename D> using type = consume_CustomerManagementAppService_IUserFactory<D>;
    };
    template <typename D>
    struct consume_CustomerManagementAppService_IUserService
    {
        WINRT_IMPL_AUTO(winrt::CustomerManagementAppService::AuthUserResultVM) GetUserByID(int32_t Id) const;
        WINRT_IMPL_AUTO(winrt::CustomerManagementAppService::AuthUserResultVM) AuthenticateUser(param::hstring const& username, param::hstring const& password, int64_t companyId) const;
        WINRT_IMPL_AUTO(winrt::CustomerManagementAppService::AuthUserResultVM) CreateUser(param::hstring const& username, param::hstring const& password, int64_t companyId) const;
    };
    template <> struct consume<winrt::CustomerManagementAppService::IUserService>
    {
        template <typename D> using type = consume_CustomerManagementAppService_IUserService<D>;
    };
}
#endif
