// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210930.14

#pragma once
#ifndef WINRT_CustomerManagementAppService_2_H
#define WINRT_CustomerManagementAppService_2_H
#include "winrt/impl/CustomerManagementAppService.1.h"
WINRT_EXPORT namespace winrt::CustomerManagementAppService
{
    struct __declspec(empty_bases) Class : winrt::CustomerManagementAppService::IClass
    {
        Class(std::nullptr_t) noexcept {}
        Class(void* ptr, take_ownership_from_abi_t) noexcept : winrt::CustomerManagementAppService::IClass(ptr, take_ownership_from_abi) {}
        Class();
    };
}
#endif
