// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementApp_1_H
#define WINRT_CustomerManagementApp_1_H
#include "winrt/impl/CustomerManagementApp.0.h"
WINRT_EXPORT namespace winrt::CustomerManagementApp
{
}
#endif
