// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementApp_0_H
#define WINRT_CustomerManagementApp_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::CustomerManagementApp
{
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::CustomerManagementApp::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::CustomerManagementApp::XamlMetaDataProvider> = L"CustomerManagementApp.XamlMetaDataProvider";
    template <> struct default_interface<winrt::CustomerManagementApp::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
}
#endif
