// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_CustomerManagementApp_2_H
#define WINRT_CustomerManagementApp_2_H
#include "winrt/impl/Windows.UI.Xaml.Markup.1.h"
#include "winrt/impl/CustomerManagementApp.1.h"
WINRT_EXPORT namespace winrt::CustomerManagementApp
{
    struct __declspec(empty_bases) XamlMetaDataProvider : winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
